# -*- coding: utf-8 -*-
"""Error handling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HoRKEHoIXK14fVAzP3_fj4pzEBC0lDh-
"""

#The try, except, finally Structure
try:
  x=int("hello")
except:
  print("Oops! That was not a number.")
finally:
  print("Execution")

#ValueError
''' Occurs when a function receives the right type of argument but the wrong value. '''
try:
  num=int("xyz")
except:
  print("Invalid value provided")

#2. TypeError
''' Occurs when an operation is applied to the wrong type.'''
try:
  result="hello"+5
except:
  print("Type mismatch error!")

#3.IndexError
''' Occurs when accessing an invalid index in a list. '''
try:
  my_list=[1,2,3]
  print(my_list=[5])
except:
  print("index out of bound!")

#Multiple Exceptions
'''' You can handle different errors separately: '''
try:
  value=int("xyz")
  my_list=[1,2,3]
  print(my_list[10])
except ValueError:
  print("conversion failed!")
except IndexError:
  print("List index error!")

