# -*- coding: utf-8 -*-
"""Example of text function

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mt0FIb_WZCTLlWov7naAADMtro_uUluv
"""

with open("Gayathri.txt","w") as file:
  file.write("Hello Gayathri!")
  file.write("\nI am 20 yrs old")

with open("Gayathri.txt","a") as file:
  file.write("\nBSC is my department")

with open("Gayathri.txt","r") as file:
  for line in file:
    print(line.strip())

with open("Gayathri.txt","r") as file:
  lines=file.readlines()
  print(lines)

with open("Gayathri.txt","r+") as file:
  content=file.read()
  file.write("\nI love to travel")

