# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RdHjee9c15cfyUV8x7FlRyH9XzjXdoYS
"""

a=["a","b","c","d","e","f"]
print(a)

a.clear()
print(a)

x = a.remove('f')
print(x)
print(a)

print(a)

a.pop(2)
print(a)

m = a.pop(0)
print(m)
print(a)

n = a.pop()
print(n)
print(a)

print(len(a))

length = len(a)
print(length)

a=['1','2','3','4','5','6']
print(len(a))

count = 0
for i in a:
  count = count + 1
print(count)

print(type(a))

my_var = '5'
my_list = list((my_var))
print(my_list)

print(type(my_list))

a=['1','2','3','4','5','6']
position = 0
for i in a:
  if(i=="4"):
    print(position)
  position = position +1

fruits = ['apple', 'banana', 'orange', 'kiwi', 'cherry', 'papaya', 'pear', 'cherry']

position = 0
for i in fruits:
#  if(i=='cherry'):
#   print(position)
  print(i)
#position = position + 1|

for i in range(0, len(fruits)):
  print(fruits[i])

# Python list of 120 fruits (with repetitions)
fruits = [
    "Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Blueberry", "Papaya", "Guava",
    "Watermelon", "Kiwi", "Peach", "Pear", "Plum", "Cherry", "Apricot", "Lychee", "Fig", "Pomegranate",
    "Coconut", "Dragonfruit", "Raspberry", "Blackberry", "Mulberry", "Jackfruit", "Custard Apple", "Starfruit", "Passionfruit", "Tangerine",
    "Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Blueberry", "Papaya", "Guava",
    "Watermelon", "Kiwi", "Peach", "Pear", "Plum", "Cherry", "Apricot", "Lychee", "Fig", "Pomegranate",
    "Coconut", "Dragonfruit", "Raspberry", "Blackberry", "Mulberry", "Jackfruit", "Custard Apple", "Starfruit", "Passionfruit", "Tangerine",
    "Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Blueberry", "Papaya", "Guava",
    "Watermelon", "Kiwi", "Peach", "Pear", "Plum", "Cherry", "Apricot", "Lychee", "Fig", "Pomegranate",
    "Coconut", "Dragonfruit", "Raspberry", "Blackberry", "Mulberry", "Jackfruit", "Custard Apple", "Starfruit", "Passionfruit", "Tangerine",
    "Apple", "Banana", "Orange", "Mango", "Grapes", "Pineapple", "Strawberry", "Blueberry", "Papaya", "Guava",
    "Watermelon", "Kiwi", "Peach", "Pear", "Plum", "Cherry", "Apricot", "Lychee", "Fig", "Pomegranate",
    "Coconut", "Dragonfruit", "Raspberry", "Blackberry", "Mulberry", "Jackfruit", "Custard Apple", "Starfruit", "Passionfruit", "Tangerine"
]

print(len(fruits))  # This will print 120

apple_count = fruits.count('Apple')
print(apple_count)

Pear_count = fruits.count('Pear')
print(Pear_count)

fruits.index('Mango')

fruits.sort()

print(fruits)

fruits.reverse()

print(fruits)

# Python list of 120 numbers (with repetitions)
numbers = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 99, 100,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20
]

print(len(numbers))  # This will print 120

numbers.sort()
print(numbers)

numbers.reverse()
print(numbers)

numbers.index(6)

print('Papaya'not in fruits)

print('Lemon' not in fruits)

print('Papaya' in fruits)

print('Lemon' in fruits)

