# -*- coding: utf-8 -*-
"""Recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Eho-4W7ELsCiQiVtSRUFW0RJV5Fc0n-
"""

#Print numbers from 1 to n using recursion.
#Example: Input = 5 → Output = 1 2 3 4 5
def print_numbers(n, current=1):
    if current > n:
        return
    print(current, end=" ")
    print_numbers(n, current + 1)
n = 9
print_numbers(n)

#Reverse a string using recursion.
#Example: Input = "hello" → Output = "olleh"
def reverse_string(s):
    if len(s) <= 1:
        return s
    return reverse_string(s[1:]) + s[0]
text = "Gahan"
print(reverse_string(text))

#3.	Find the greatest common divisor (GCD) of two numbers using recursion.
def gcd(a, b):
    if b == 0:
        return a
    return gcd(b, a % b)
x, y = 48, 18
print("GCD of", x, "and", y, "is:", gcd(x, y))

#4.	Check if a number is a palindrome using recursion.
#Example: Input = 121 → Output = True
def is_palindrome(s):
    s = str(s)
    if len(s) <= 1:
        return True
    if s[0] != s[-1]:
        return False
    return is_palindrome(s[1:-1])
print(is_palindrome(121))
print(is_palindrome(123))

#Count digits of a number using recursion.
#Example: Input = 12345 → Output = 5
def count_digits(n):
    if n == 0:
        return 0
    return 1 + count_digits(n // 10)
num = 98765
print("Number of digits:", count_digits(num))

