# -*- coding: utf-8 -*-
"""Text file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Jxl_5r3vTVcq3Yf8JcWl7XR4O8A80UD
"""

with open("first_file.txt", "w") as file:
  file.write("Hello world")

with open("first_file.txt", "w") as file:
  file.write("I like Sunflower")

with open("first_file.txt", "a") as file:
  file.write("\n I like Lily")

with open ("first_file.txt","r") as file:
  reading = file.read()
  print(reading)

with open ("first_file.txt","r") as file:
  for line in file:
    print(line.strip())

with open ("first_file.txt","r") as file:
  reading = file.readlines()
  print(reading)

with open("barbie_file.txt","w") as file:
  file.write("I an Barbie girl")

with open("barbie_file.txt","a") as file:
  file.write("\n In the barbie world")

with open("barbie_file.txt","r") as file:
  reading = file.read()
  print(reading)

with open("barbie_file.txt","r+") as file :
  #reading = file.read()
  #print(reading)
  file.write("life in plastic is fantastic")
  reading2=file.read()
  print(reading2)

